### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by austburn** [nathanbraun/code-soccer-files#1]
https://github.com/nathanbraun/code-soccer-files/blob/cca50101e4cc9eb585c93f2e53da5aa01f935468/code/03_02_functions.py#L19

I wasn't able to work through this example as shown. After inspecting the DataFrame and debugging a bit, I noticed that `pg[['side']]` contains strings and integers/NaN. I tried converting that to a string like on line 14, but led me to new issues with not being able to take the mean of strings.

`pg.mean(numeric_only=True)` seems to simplify this a bit.

**Comment by nathanbraun** [comment]
Just fixed this -- thank you!
