### ISSUE TITLE
One to Many Example

### ISSUE THREAD

**Issue by austburn** [nathanbraun/code-soccer-files#2]
The one to many example in section 3.5 was a little confusing to me. `combined` ends up being our "left" table, which has many duplicated `player_id` that match to single `player_id`s in the `player` table. To me, this seems more like many-to-one?

This is further illustrated by passing `validate='1:m'`:
```python
In [70]: pd.merge(combined, player[['player_id', 'player_name', 'pos', 'team']], validate='1:m')
Traceback (most recent call last):

  Cell In[70], line 1
    pd.merge(combined, player[['player_id', 'player_name', 'pos',

  File ~/anaconda3/lib/python3.11/site-packages/pandas/core/reshape/merge.py:148 in merge
    op = _MergeOperation(

  File ~/anaconda3/lib/python3.11/site-packages/pandas/core/reshape/merge.py:747 in __init__
    self._validate(validate)

  File ~/anaconda3/lib/python3.11/site-packages/pandas/core/reshape/merge.py:1590 in _validate
    raise MergeError(

MergeError: Merge keys are not unique in left dataset; not a one-to-many merge
```

Just reversing the arguments works and passes validation, however the columns aren't in a more human-readable order (to be expected).

```python
In   [71]: pd.merge(player[['player_id', 'player_name', 'pos', 'team']], combined, validate='1:m').head()
Out[71]: 
   player_id      player_name  pos     team  match_id  pass  assist  shot  goal
0      32793       A. N'Diaye  MID  Senegal   2057996    28       0     0     0
1      32793       A. N'Diaye  MID  Senegal   2057999    16       0     0     0
2         36  T. Alderweireld  DEF  Belgium   2057990   105       0     0     0
3         36  T. Alderweireld  DEF  Belgium   2057992    53       1     2     0
4         36  T. Alderweireld  DEF  Belgium   2058007    77       0     0     0
```

**Comment by nathanbraun** [comment]
Thanks for reporting this @austburn.  Really m:1 and 1:m merges are the same.  I think of it being three types of merges:

1. 1:1
2. 1:m
3. m:m

We're talking about (2) here.  I also lump m:1 in with this category, since order doesn't really matter.  I tried to make this clear in the book by always saying something like "If you're doing a 1:many (or many:1) join then..." but I'll take a look at this again and make sure it's clear.  Thanks again for the note!
